import "./globals.css";
import axios from "axios";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-gray-800">
        <main className="max-w-4xl m-auto py-6 px-3">{children}</main>
      </body>
    </html>
  );
}
